# Generated by Django 2.2.16 on 2022-11-07 13:54

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20221107_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': 'Произведение', 'verbose_name_plural': 'Произведения'},
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(db_index=True, help_text='Введите год релиза', validators=[reviews.validators.validate_year], verbose_name='Год релиза'),
        ),
    ]
